name: Gigantic
main: com.github.unchama.gigantic.Gigantic
version: 0.0.8
description: Gigantic Seichi Server Plugin
softdepend: [PlaceholderAPI]



commands:
  gacha:
      description: This is gacha command.
      usage: /<command> <help>
      aliases: [gc, seichigacha]
      default: op
      permission: gigantic.gacha
      permission-message: You don't have <permission>
  debug:
      description: This is debug command.
      usage: /<command> <help>
      aliases: [gigadebug,giganticdebug]
      default: op
      permission: gigantic.debug
      permission-message: You don't have <permission>
