name: Gigantic
main: com.github.unchama.gigantic.Gigantic
version: 1.0.0

commands:
  gacha:
      description: This is a gacha command.
      usage: /<command> <help>
      permission: multiseichiplugin.seichi
      permission-message: You don't have <permission>
