name: Gigantic
main: com.github.unchama.gigantic.Gigantic
version: 0.0.8
description: Gigantic Seichi Server Plugin
softdepend: [PlaceholderAPI]



commands:
  gacha:
      description: This is a gacha command.
      usage: /<command> <help>
      aliases: [gc, seichigacha]
      permission: gigantic.gacha
      permission-message: You don't have <permission>
